---
name: DynamicShopUI
main: BreathTakinglyBinary\DynamicShopUI\DynamicShopUI
api: 3.2.0
version: 1.0.4
depend: [EconomyAPI]
author: FiberglassCivic(95CivicSi)

"permissions": {
        "dsu": {
            "default": "op",
            "description": "Allows access to all DynamicShopUI features.",
            "children": {
                "dsu.configuration": {
                    "default": "op",
                    "description": "Allows modifying the configuration in-game."
                },
                "dsu.command": {
                    "default": "op",
                    "description": "Allows access to all DSU command features.",
                    "children": {
                        "dsu.command.manage": {
                            "default": "op",
                            "description": "Allows user to manage buy/sell options for the shop."
                        },
                        "dsu.command.sell": {
                            "default": "op",
                            "description": "Allows the use of all sell options.",
                            "children": {
                                "dsu.command.sell.all": {
                                    "default": "op",
                                    "description": "Allows players to use the sell all command."
                                },
                                "dsu.command.sell.hand": {
                                    "default": true,
                                    "description": "Allows players to use the sell all command."
                                }
                            }
                        },
                        "dsu.command.shop": {
                            "default": true,
                            "description": "Allows access to the Shop UI so players can buy items."
                        }
                    }
                }
            }
        }
    }
...
